### ISSUE TITLE
Tracking: hera V5 syntactic sugar

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#447]
5.0

- [x] Support templates
  - [x] Dag
  - [x] DagTask
  - [x] Steps
  - [x] Step
  - [x] ParallelStep
  - [x] Suspend
  - [x] Script
  - [x] Container
  - [x] Resource
  - [x] ContainerSet
  - [x] Data
  - [x] HTTP
- [x] add_template/add_step/add_task functions in post init
- [x] Set entrypoint with support for passing template

5.1 - 

- [x] Template to step/task callable
- [ ] Pythonic with_items/with_params

**Comment by samj1912** [comment]
Fixed by #437
